name: 'Bit Dependency Update'
description: 'Check for new updates of Bit components and create Pull Request with the updates.'
branding: 
  icon: 'shield'
  color: 'purple'
inputs:
  ws-dir:
    description: "Workspace json file directory path"
    required: false
  allow:
    description: "Allow different types of dependencies. Values 'all', 'packages', 'components', 'envs'"
    required: false
    default: "all"
  branch:
    description: "Branch to check for dependency update"
    required: false
    defaults: "main"
  git-user-name:
    description: "Git user name"
    required: true
  git-user-email:
    description: "Git user email"
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
